"""add_trigger_system

Revision ID: 0d9538be39e0
Revises: 7844d811d9cc
Create Date: 2025-12-23 21:24:32.597832

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9538be39e0'
down_revision: Union[str, Sequence[str], None] = '7844d811d9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# System principal ID used for seed data
SYSTEM_PRINCIPAL_ID = "a603702c-1e2f-4324-bd98-3c8e3232b477"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_index(op.f('ix_simulation_configs_is_paused'), 'simulation_configs', ['is_paused'], unique=False)
    op.create_table('agent_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_triggers_agent_id'), 'agent_triggers', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_triggers_is_active'), 'agent_triggers', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_triggers_simulation_id'), 'agent_triggers', ['simulation_id'], unique=False)
    op.create_table('agent_trigger_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('matched_conditions', sa.JSON(), nullable=True),
    sa.Column('agent_executed', sa.Boolean(), nullable=False),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['agent_triggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_trigger_events_agent_id'), 'agent_trigger_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_trigger_events_created_at'), 'agent_trigger_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_trigger_events_trigger_id'), 'agent_trigger_events', ['trigger_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the trigger server
    conn = op.get_bind()

    # Check if trigger server already exists
    existing = conn.execute(
        sa.text("SELECT 1 FROM servers WHERE name = 'trigger'")
    ).fetchone()

    if not existing:
        conn.execute(
            sa.text(
                "INSERT INTO servers (name, description, server_type, transport, command, args, "
                "created_by_principal_id, is_active, created_at) "
                "VALUES (:name, :description, :server_type, :transport, :command, :args, "
                ":created_by_principal_id, true, NOW())"
            ),
            {
                "name": "trigger",
                "description": "Event trigger tools: subscribe to database events and get triggered automatically.",
                "server_type": "system",
                "transport": "stdio",
                "command": "uv",
                "args": json.dumps(["run", "python", "-m", "src.mcp_servers.servers.trigger_server"]),
                "created_by_principal_id": SYSTEM_PRINCIPAL_ID,
            }
        )
        conn.commit()

    # Grant trigger server to all existing agents
    server_id = conn.execute(
        sa.text("SELECT id FROM servers WHERE name = 'trigger'")
    ).fetchone()

    if server_id:
        server_id = server_id[0]
        agent_ids = conn.execute(sa.text("SELECT id FROM agents")).fetchall()

        for agent_row in agent_ids:
            agent_id = agent_row[0]
            # Check if grant already exists
            exists = conn.execute(
                sa.text(
                    "SELECT 1 FROM agent_servers WHERE agent_id = :agent_id AND server_id = :server_id"
                ),
                {"agent_id": agent_id, "server_id": server_id}
            ).fetchone()
            if not exists:
                conn.execute(
                    sa.text(
                        "INSERT INTO agent_servers (agent_id, server_id, granted_at) "
                        "VALUES (:agent_id, :server_id, NOW())"
                    ),
                    {"agent_id": agent_id, "server_id": server_id}
                )
        conn.commit()

    # Create SimulationConfig for existing simulations
    simulation_ids = conn.execute(sa.text("SELECT id FROM simulations")).fetchall()
    for sim_row in simulation_ids:
        sim_id = sim_row[0]
        exists = conn.execute(
            sa.text("SELECT 1 FROM simulation_configs WHERE simulation_id = :sim_id"),
            {"sim_id": sim_id}
        ).fetchone()
        if not exists:
            conn.execute(
                sa.text(
                    "INSERT INTO simulation_configs (simulation_id, is_paused, config_json, created_at, updated_at) "
                    "VALUES (:sim_id, false, '{}', NOW(), NOW())"
                ),
                {"sim_id": sim_id}
            )
    conn.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_trigger_events_trigger_id'), table_name='agent_trigger_events')
    op.drop_index(op.f('ix_agent_trigger_events_created_at'), table_name='agent_trigger_events')
    op.drop_index(op.f('ix_agent_trigger_events_agent_id'), table_name='agent_trigger_events')
    op.drop_table('agent_trigger_events')
    op.drop_index(op.f('ix_agent_triggers_simulation_id'), table_name='agent_triggers')
    op.drop_index(op.f('ix_agent_triggers_is_active'), table_name='agent_triggers')
    op.drop_index(op.f('ix_agent_triggers_agent_id'), table_name='agent_triggers')
    op.drop_table('agent_triggers')
    op.drop_index(op.f('ix_simulation_configs_is_paused'), table_name='simulation_configs')
    op.drop_table('simulation_configs')
    # ### end Alembic commands ###
