"""simplify_agents

Revision ID: 14bbe3e2fd0b
Revises: f20c1f86da82
Create Date: 2025-12-30 18:05:06.142359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14bbe3e2fd0b'
down_revision: Union[str, Sequence[str], None] = 'f20c1f86da82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_trigger_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('agent_tool_usage')
    op.drop_table('agent_servers')
    op.drop_index(op.f('ix_simulation_configs_is_paused'), table_name='simulation_configs')
    op.drop_table('simulation_configs')
    op.drop_table('servers')
    op.drop_constraint(op.f('agent_model_usage_agent_task_id_fkey'), 'agent_model_usage', type_='foreignkey')
    op.drop_column('agent_model_usage', 'agent_task_id')
    op.drop_index(op.f('ix_agent_triggers_simulation_id'), table_name='agent_triggers')
    op.drop_constraint(op.f('agent_triggers_simulation_id_fkey'), 'agent_triggers', type_='foreignkey')
    op.drop_column('agent_triggers', 'simulation_id')
    op.add_column('simulations', sa.Column('is_paused', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulations', 'is_paused')
    op.add_column('agent_triggers', sa.Column('simulation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('agent_triggers_simulation_id_fkey'), 'agent_triggers', 'simulations', ['simulation_id'], ['id'])
    op.create_index(op.f('ix_agent_triggers_simulation_id'), 'agent_triggers', ['simulation_id'], unique=False)
    op.add_column('agent_model_usage', sa.Column('agent_task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('agent_model_usage_agent_task_id_fkey'), 'agent_model_usage', 'agent_tasks', ['agent_task_id'], ['id'])
    op.create_table('servers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_by_principal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('server_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transport', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('command', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('env', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_principal_id'], ['principals.id'], name='servers_created_by_principal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='servers_pkey'),
    sa.UniqueConstraint('name', name='servers_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('simulation_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('simulation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_paused', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('simulation_configs_simulation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('simulation_configs_pkey')),
    sa.UniqueConstraint('simulation_id', name=op.f('simulation_configs_simulation_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_simulation_configs_is_paused'), 'simulation_configs', ['is_paused'], unique=False)
    op.create_table('agent_servers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_servers_agent_id_fkey')),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('agent_servers_server_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_servers_pkey'))
    )
    op.create_table('agent_tool_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('input', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('server_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_tool_usage_agent_id_fkey')),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], name=op.f('agent_tool_usage_agent_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_tool_usage_pkey'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('change_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matched_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('agent_executed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('agent_runs_agent_id_fkey')),
    sa.ForeignKeyConstraint(['trigger_id'], ['agent_triggers.id'], name=op.f('agent_runs_trigger_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_runs_pkey'))
    )
    op.create_index(op.f('ix_agent_runs_trigger_id'), 'agent_runs', ['trigger_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    # ### end Alembic commands ###
